### ISSUE TITLE
OpenFietsMap not rendering as a node shops which have a cycle department.

### ISSUE THREAD

**Issue by Nick-Tallguy** [ligfietser/mkgmap-style-sheets#5]
Shops such as Decathlon or Halfords which have a large cycling department are not appearing as an icon on the ofm or ofml maps for a garmin.

Adding 
     `shop=* & (service:bicycle:retail=yes | service:bicycle:repair=yes | service:bicycle:tools=yes)  [0x2f03 resolution 22]`
in the points file of the style folder added it for me, for those shops that have this additional tagging. I've added it at line 47.

Regards & thanks for your work on this.

**Comment by ligfietser** [comment]
I'll add it, thanks for your help, very much appreciated!
