### ISSUE TITLE
TYP file 10010 OFM full version

### ISSUE THREAD

**Issue by enginefeeder101** [ligfietser/mkgmap-style-sheets#7]
Hi @ligfietser,
Thanks for your very nice cycle maps. I noticed the typ file definition (10010.txt / 10010.typ) for the OpenFietsMap full version is missing from this repo. Would it be possible to share that?

**Comment by ligfietser** [comment]
It is exactly the same as the Openfietsmap lite/20011.txt  and 20011.TYP

**Comment by enginefeeder101** [comment]
Thanks for the quick notice!
